# backend/models/response_models.py
"""
FinThesisGuard AI — API Response Models
ArkAngel Financial Solutions

Pydantic v2 schemas for all outgoing API responses.
Used by all pipeline stages and FastAPI route handlers.
"""

import time
from datetime import datetime, timezone
from typing import Any, Literal, Optional
from pydantic import BaseModel, Field, field_validator, computed_field


# ─────────────────────────────────────────────
# ENUMS & LITERALS
# ─────────────────────────────────────────────

ConfidenceLevel = Literal["High", "Medium", "Low"]
ConflictSeverity = Literal["Minor", "Moderate", "Major"]
ServiceStatus   = Literal["ok", "degraded", "unavailable", "unknown"]


# ─────────────────────────────────────────────
# 1. Citation
# ─────────────────────────────────────────────

class Citation(BaseModel):
    """
    Represents a single retrieved source document used in an answer.
    Attached to every QueryResponse and ThesisResponse.
    """

    id: int = Field(
        ...,
        ge=1,
        description="Citation number used inline in answer as [1], [2] etc.",
    )
    title: str = Field(
        ...,
        max_length=500,
        description="Document title or heading",
        examples=["HDFC Bank Q3 FY26 Earnings Call Transcript"],
    )
    source_type: str = Field(
        ...,
        description="Authority type: rbi, sebi, annual_report, earnings_transcript, etc.",
        examples=["annual_report", "sebi", "rbi", "broker_research"],
    )
    date: str = Field(
        default="unknown",
        description="Publication date in YYYY-MM-DD or YYYY-MM or YYYY format",
        examples=["2026-01-15", "2025-10", "2025"],
    )
    authority_weight: float = Field(
        default=1.0,
        ge=0.0,
        le=2.0,
        description="Source authority weight used in re-ranking (0.0–2.0)",
    )
    relevance_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Final re-ranked relevance score (0.0–1.0)",
    )
    url: Optional[str] = Field(
        default=None,
        description="Source URL if publicly available",
        examples=["https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=12345"],
    )
    excerpt: str = Field(
        default="",
        max_length=1000,
        description="Relevant excerpt from the source document",
    )
    company: Optional[str] = Field(
        default=None,
        description="Company name if document is company-specific",
        examples=["HDFC Bank", "TCS"],
    )
    sector: Optional[str] = Field(
        default=None,
        description="Industry sector of the source document",
        examples=["banking", "technology", "pharma"],
    )

    @field_validator("source_type")
    @classmethod
    def normalize_source_type(cls, v: str) -> str:
        return v.lower().strip()

    @field_validator("relevance_score", "authority_weight")
    @classmethod
    def round_scores(cls, v: float) -> float:
        return round(v, 4)

    @computed_field
    @property
    def authority_label(self) -> str:
        """Human-readable label for the source authority."""
        labels = {
            "rbi":                  "RBI",
            "sebi":                 "SEBI",
            "mca":                  "MCA",
            "annual_report":        "Annual Report",
            "earnings_transcript":  "Earnings Transcript",
            "broker_research":      "Broker Research",
            "tax_law":              "Tax Law",
            "news":                 "News",
            "blog":                 "Blog",
            "unknown":              "Unknown",
        }
        return labels.get(self.source_type, self.source_type.upper())

    @computed_field
    @property
    def is_regulatory(self) -> bool:
        """True if source is a regulatory authority (RBI/SEBI/MCA)."""
        return self.source_type in {"rbi", "sebi", "mca", "tax_law"}


# ─────────────────────────────────────────────
# 2. Conflict
# ─────────────────────────────────────────────

class Conflict(BaseModel):
    """
    Represents a detected contradiction between two sources
    on the same metric/field. Generated by Agent 4.
    """

    field: str = Field(
        ...,
        description="The financial metric where conflict was detected",
        examples=["NPA ratio", "NIM", "Revenue", "CASA ratio"],
    )
    source_a: str = Field(
        ...,
        description="Name/title of the first source",
        examples=["HDFC Bank Q3 FY26 Annual Report"],
    )
    value_a: str = Field(
        ...,
        description="Value reported by source A",
        examples=["1.26%", "₹45,000 crore", "4.2%"],
    )
    source_b: str = Field(
        ...,
        description="Name/title of the second (conflicting) source",
        examples=["Motilal Oswal HDFC Research Note"],
    )
    value_b: str = Field(
        ...,
        description="Value reported by source B (conflicts with value_a)",
        examples=["1.34%", "₹43,200 crore", "4.5%"],
    )
    recommended_source: str = Field(
        ...,
        description="The source Agent 4 recommends as more reliable",
    )
    reason: str = Field(
        ...,
        description="Explanation of why one source is preferred over the other",
        examples=[
            "Source A is more recent (Jan 2026 vs Oct 2025) and directly from the company.",
            "Source A is a primary regulatory document with higher authority weight.",
        ],
    )
    severity: ConflictSeverity = Field(
        default="Minor",
        description="Severity: Minor (<5% diff), Moderate (5–20%), Major (>20%)",
    )
    date_a: Optional[str] = Field(
        default=None,
        description="Publication date of source A",
    )
    date_b: Optional[str] = Field(
        default=None,
        description="Publication date of source B",
    )

    @computed_field
    @property
    def conflict_summary(self) -> str:
        """One-line summary of the conflict for UI display."""
        return (
            f"{self.field}: {self.source_a} says {self.value_a} "
            f"vs {self.source_b} says {self.value_b}"
        )


# ─────────────────────────────────────────────
# 3. DataGap
# ─────────────────────────────────────────────

class DataGap(BaseModel):
    """
    Represents a piece of information the system could not find
    in the retrieved corpus. Signals knowledge limitations.
    """

    description: str = Field(
        ...,
        description="What information is missing",
        examples=["Q4 FY26 NPA data not available in corpus"],
    )
    impact: Literal["High", "Medium", "Low"] = Field(
        default="Low",
        description="How much this gap impacts answer quality",
    )
    suggested_source: Optional[str] = Field(
        default=None,
        description="Where this data could be found",
        examples=["BSE filing", "RBI database", "Company investor relations"],
    )


# ─────────────────────────────────────────────
# 4. AgentTrace
# ─────────────────────────────────────────────

class AgentTrace(BaseModel):
    """
    Execution trace for a single agent — attached to QueryResponse
    when debug_mode is enabled. Useful for pipeline debugging.
    """

    agent_name: str
    duration_ms: float
    success: bool
    input_summary: Optional[str] = None
    output_summary: Optional[str] = None
    error: Optional[str] = None

    @computed_field
    @property
    def status_label(self) -> str:
        if not self.success:
            return "FAILED"
        if self.duration_ms > 1000:
            return "SLOW"
        return "OK"


# ─────────────────────────────────────────────
# 5. QueryResponse
# ─────────────────────────────────────────────

class QueryResponse(BaseModel):
    """
    Complete response for a financial RAG query.
    Returned by POST /api/query.
    Contains answer, citations, conflicts, confidence, and metadata.
    """

    answer: str = Field(
        ...,
        description="The synthesized answer with inline citation markers [1], [2] etc.",
    )
    citations: list[Citation] = Field(
        default_factory=list,
        description="List of source documents used in the answer",
    )
    confidence: ConfidenceLevel = Field(
        ...,
        description="Overall answer confidence based on source agreement and coverage",
    )
    reasoning: str = Field(
        default="",
        description="Agent's step-by-step reasoning chain (shown in collapsible UI panel)",
    )
    conflicts: list[Conflict] = Field(
        default_factory=list,
        description="List of detected contradictions across sources",
    )
    data_gaps: list[str] = Field(
        default_factory=list,
        description="Information the system could not find in the corpus",
    )
    latency_ms: int = Field(
        default=0,
        ge=0,
        description="Total pipeline execution time in milliseconds",
    )
    agents_used: list[str] = Field(
        default_factory=list,
        description="Names of agents that processed this query",
    )
    query_type: str = Field(
        default="UNKNOWN",
        description="Classified query type: FACTUAL, COMPARATIVE, REGULATORY, THESIS",
    )
    cache_hit: bool = Field(
        default=False,
        description="True if response was served from Redis cache",
    )
    sub_queries: list[str] = Field(
        default_factory=list,
        description="Decomposed sub-queries generated by Agent 2 (if applicable)",
    )
    agent_traces: list[AgentTrace] = Field(
        default_factory=list,
        description="Per-agent execution traces (populated in debug mode only)",
    )
    request_id: Optional[str] = Field(
        default=None,
        description="Unique request ID for tracing and support",
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="UTC timestamp when response was generated",
    )

    # ── Computed Fields ───────────────────────

    @computed_field
    @property
    def citation_count(self) -> int:
        return len(self.citations)

    @computed_field
    @property
    def conflict_count(self) -> int:
        return len(self.conflicts)

    @computed_field
    @property
    def has_conflicts(self) -> bool:
        return len(self.conflicts) > 0

    @computed_field
    @property
    def within_latency_target(self) -> bool:
        """True if response was delivered within the 3-second target."""
        return self.latency_ms <= 3000

    @computed_field
    @property
    def regulatory_sources_count(self) -> int:
        """Count of citations from RBI/SEBI/MCA sources."""
        return sum(1 for c in self.citations if c.is_regulatory)

    # ── Convenience Constructors ──────────────

    @classmethod
    def error_response(
        cls,
        error_message: str,
        request_id: Optional[str] = None,
        latency_ms: int = 0,
    ) -> "QueryResponse":
        """Creates a standardized error response."""
        return cls(
            answer=f"Unable to process query: {error_message}",
            confidence="Low",
            reasoning=f"Pipeline error: {error_message}",
            data_gaps=["Query could not be processed due to an internal error."],
            latency_ms=latency_ms,
            request_id=request_id,
        )

    @classmethod
    def insufficient_data_response(
        cls,
        query: str,
        request_id: Optional[str] = None,
        latency_ms: int = 0,
    ) -> "QueryResponse":
        """Creates a response when corpus has no relevant data."""
        return cls(
            answer=(
                "Insufficient data available in the current corpus to answer this query. "
                "The relevant documents may not have been ingested yet. "
                "Please try ingesting the relevant annual reports, RBI circulars, "
                "or research notes before querying."
            ),
            confidence="Low",
            reasoning="No relevant chunks retrieved from Pinecone above similarity threshold.",
            data_gaps=[f"No sources found for: {query[:100]}"],
            latency_ms=latency_ms,
            request_id=request_id,
        )

    model_config = {"populate_by_name": True}


# ─────────────────────────────────────────────
# 6. BatchQueryResponse
# ─────────────────────────────────────────────

class BatchQueryResponse(BaseModel):
    """Response for batch query endpoint."""

    results: list[QueryResponse]
    total_queries: int
    successful: int
    failed: int
    total_latency_ms: int

    @computed_field
    @property
    def avg_latency_ms(self) -> float:
        if not self.results:
            return 0.0
        return round(
            sum(r.latency_ms for r in self.results) / len(self.results), 1
        )


# ─────────────────────────────────────────────
# 7. ServiceHealth
# ─────────────────────────────────────────────

class ServiceHealth(BaseModel):
    """Health status of a single dependent service."""

    name: str = Field(..., description="Service name: groq, pinecone, redis")
    status: ServiceStatus = Field(..., description="Service status")
    latency_ms: Optional[float] = Field(
        default=None,
        description="Response time of health check ping",
    )
    version: Optional[str] = Field(
        default=None,
        description="Service version if available",
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if status is not 'ok'",
    )
    checked_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="UTC timestamp of health check",
    )

    @computed_field
    @property
    def is_healthy(self) -> bool:
        return self.status == "ok"


# ─────────────────────────────────────────────
# 8. HealthResponse
# ─────────────────────────────────────────────

class HealthResponse(BaseModel):
    """
    Response for GET /health endpoint.
    Shows overall system status and per-service health.
    """

    status: ServiceStatus = Field(
        ...,
        description="Overall system status",
    )
    app_name: str = Field(
        default="FinThesisGuard AI",
        description="Application name",
    )
    version: str = Field(
        ...,
        description="Application version",
        examples=["1.0.0"],
    )
    environment: str = Field(
        ...,
        description="Deployment environment: development, staging, production",
    )
    uptime_seconds: float = Field(
        default=0.0,
        description="Application uptime in seconds",
    )
    services: dict[str, ServiceHealth] = Field(
        default_factory=dict,
        description="Health status of each dependent service",
    )
    corpus_stats: Optional[dict] = Field(
        default=None,
        description="Pinecone corpus statistics: total vectors, namespaces",
    )
    cache_stats: Optional[dict] = Field(
        default=None,
        description="Redis cache statistics: hit rate, total ops",
    )
    llm_stats: Optional[dict] = Field(
        default=None,
        description="LLM usage stats: total calls, success rate, tokens used",
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
    )

    @computed_field
    @property
    def uptime_human(self) -> str:
        """Human-readable uptime string."""
        seconds = int(self.uptime_seconds)
        days, rem = divmod(seconds, 86400)
        hours, rem = divmod(rem, 3600)
        minutes, secs = divmod(rem, 60)
        if days > 0:
            return f"{days}d {hours}h {minutes}m"
        if hours > 0:
            return f"{hours}h {minutes}m {secs}s"
        if minutes > 0:
            return f"{minutes}m {secs}s"
        return f"{secs}s"

    @computed_field
    @property
    def all_services_healthy(self) -> bool:
        return all(s.is_healthy for s in self.services.values())


# ─────────────────────────────────────────────
# 9. MetricsResponse
# ─────────────────────────────────────────────

class MetricsResponse(BaseModel):
    """
    Response for GET /metrics endpoint.
    Operational metrics for monitoring dashboards.
    """

    total_queries: int = Field(default=0)
    total_thesis_validations: int = Field(default=0)
    avg_query_latency_ms: float = Field(default=0.0)
    avg_thesis_latency_ms: float = Field(default=0.0)
    cache_hit_rate_pct: float = Field(default=0.0)
    total_tokens_used: int = Field(default=0)
    estimated_cost_usd: float = Field(default=0.0)
    total_documents_ingested: int = Field(default=0)
    total_vectors_stored: int = Field(default=0)
    error_rate_pct: float = Field(default=0.0)
    uptime_seconds: float = Field(default=0.0)
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
    )


# ─────────────────────────────────────────────
# 10. IngestResponse
# ─────────────────────────────────────────────

class IngestResponse(BaseModel):
    """Response for document ingestion endpoints."""

    success: bool
    document_id: Optional[str] = None
    title: Optional[str] = None
    source_type: Optional[str] = None
    chunks_created: int = 0
    vectors_upserted: int = 0
    duration_ms: float = 0.0
    message: str = ""
    error: Optional[str] = None


# ─────────────────────────────────────────────
# EXPORTS
# ─────────────────────────────────────────────

__all__ = [
    "Citation",
    "Conflict",
    "DataGap",
    "AgentTrace",
    "QueryResponse",
    "BatchQueryResponse",
    "ServiceHealth",
    "HealthResponse",
    "MetricsResponse",
    "IngestResponse",
    "ConfidenceLevel",
    "ConflictSeverity",
    "ServiceStatus",
]
