# backend/models/thesis_models.py
"""
FinThesisGuard AI — Thesis Validation Models
ArkAngel Financial Solutions

Pydantic v2 schemas for investment thesis validation output.
Used by Agent 6 (Thesis Analyzer), Agent 7 (Stress Synthesizer),
and the thesis validation pipeline.
"""

from datetime import datetime, timezone
from typing import Literal, Optional
from pydantic import BaseModel, Field, field_validator, model_validator, computed_field

from backend.models.response_models import Citation, ConfidenceLevel
from backend.config import (
    THESIS_STRENGTH_THRESHOLDS,
    THESIS_RISK_DIMENSIONS,
    THESIS_MAX_ASSUMPTIONS,
    THESIS_MAX_BREAK_CONDITIONS,
)


# ─────────────────────────────────────────────
# ENUMS & LITERALS
# ─────────────────────────────────────────────

ThesisStrength      = Literal["Strong", "Medium", "Weak"]
StructuralRobustness = Literal["High", "Medium", "Low"]
BreakProbability    = Literal["High", "Medium", "Low"]
AssumptionCategory  = Literal[
    "demand",
    "margin",
    "valuation",
    "regulatory",
    "macro",
    "competitive",
    "operational",
    "financial",
    "unknown",
]
RiskDimension = Literal[
    "demand_risk",
    "margin_risk",
    "valuation_risk",
    "regulatory_risk",
    "macro_risk",
    "competitive_risk",
]


# ─────────────────────────────────────────────
# 1. Assumption
# ─────────────────────────────────────────────

class Assumption(BaseModel):
    """
    A single extracted assumption from the investment thesis.
    Generated by Agent 6 (Thesis Analyzer).

    Each assumption represents a causal claim the thesis depends on.
    Example: "AI demand from hyperscalers will grow 30%+ YoY"
    """

    id: int = Field(
        ...,
        ge=1,
        le=THESIS_MAX_ASSUMPTIONS,
        description="Assumption sequence number (1 to max)",
    )
    text: str = Field(
        ...,
        min_length=10,
        max_length=500,
        description="The assumption statement extracted from the thesis",
        examples=[
            "Hyperscaler AI capex will grow 25%+ in FY27",
            "HDFC Bank CASA ratio will stay above 40%",
            "RBI will not tighten LCR norms in next 12 months",
        ],
    )
    category: AssumptionCategory = Field(
        default="unknown",
        description="Type of assumption: demand, margin, valuation, regulatory, macro, etc.",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Agent's confidence that this assumption is valid (0.0–1.0)",
    )
    historical_support: bool = Field(
        ...,
        description="True if historical data in corpus supports this assumption",
    )
    supporting_evidence: list[str] = Field(
        default_factory=list,
        max_length=5,
        description="List of evidence snippets from corpus supporting/refuting this assumption",
        examples=[["HDFC Bank CASA was 41.9% in Q3 FY26 (Annual Report 2026)"]],
    )
    dependency_on: list[int] = Field(
        default_factory=list,
        description="IDs of other assumptions this one depends on",
    )
    is_critical: bool = Field(
        default=False,
        description="True if thesis completely breaks if this assumption fails",
    )

    @field_validator("text", mode="before")
    @classmethod
    def normalize_text(cls, v: str) -> str:
        return v.strip() if isinstance(v, str) else v

    @field_validator("confidence")
    @classmethod
    def round_confidence(cls, v: float) -> float:
        return round(v, 3)

    @computed_field
    @property
    def confidence_label(self) -> ConfidenceLevel:
        """Maps float confidence to High/Medium/Low label."""
        if self.confidence >= 0.7:
            return "High"
        if self.confidence >= 0.4:
            return "Medium"
        return "Low"

    @computed_field
    @property
    def risk_flag(self) -> str:
        """UI flag for assumption card color coding."""
        if not self.historical_support and self.is_critical:
            return "critical"
        if not self.historical_support:
            return "warning"
        if self.confidence < 0.4:
            return "caution"
        return "supported"


# ─────────────────────────────────────────────
# 2. RiskScore
# ─────────────────────────────────────────────

class RiskScore(BaseModel):
    """
    Risk score for a single dimension of the investment thesis.
    Generated by Agent 7 (Stress Synthesizer).

    Score 1–10: 1 = minimal risk, 10 = severe/thesis-breaking risk.
    """

    dimension: str = Field(
        ...,
        description="Risk dimension name",
        examples=THESIS_RISK_DIMENSIONS,
    )
    score: int = Field(
        ...,
        ge=1,
        le=10,
        description="Risk score from 1 (low) to 10 (critical)",
    )
    rationale: str = Field(
        ...,
        min_length=20,
        max_length=1000,
        description="Agent's explanation of the risk score",
        examples=[
            "Valuation risk is high (9/10) because the stock trades at 35x FY27E "
            "earnings, well above its 5-year average of 22x, leaving little margin "
            "of safety if earnings miss by even 5%."
        ],
    )
    supporting_data: list[str] = Field(
        default_factory=list,
        max_length=5,
        description="Data points from corpus used to justify this risk score",
    )
    related_assumption_ids: list[int] = Field(
        default_factory=list,
        description="IDs of assumptions this risk score relates to",
    )

    @field_validator("dimension")
    @classmethod
    def validate_dimension(cls, v: str) -> str:
        return v.lower().strip().replace(" ", "_")

    @computed_field
    @property
    def severity_label(self) -> Literal["Critical", "High", "Medium", "Low"]:
        """Maps score to severity label."""
        if self.score >= 9:
            return "Critical"
        if self.score >= 7:
            return "High"
        if self.score >= 4:
            return "Medium"
        return "Low"

    @computed_field
    @property
    def severity_color(self) -> Literal["red", "orange", "yellow", "green"]:
        """UI color for risk ring component."""
        if self.score >= 8:
            return "red"
        if self.score >= 6:
            return "orange"
        if self.score >= 4:
            return "yellow"
        return "green"

    @computed_field
    @property
    def dimension_label(self) -> str:
        """Human-readable dimension name for UI display."""
        labels = {
            "demand_risk":      "Demand Risk",
            "margin_risk":      "Margin Risk",
            "valuation_risk":   "Valuation Risk",
            "regulatory_risk":  "Regulatory Risk",
            "macro_risk":       "Macro Risk",
            "competitive_risk": "Competitive Risk",
        }
        return labels.get(self.dimension, self.dimension.replace("_", " ").title())


# ─────────────────────────────────────────────
# 3. BreakCondition
# ─────────────────────────────────────────────

class BreakCondition(BaseModel):
    """
    A specific, measurable event that would invalidate the thesis.
    Generated by Agent 7 (Stress Synthesizer).

    Each break condition is actionable — the investor can monitor
    the trigger metric and exit/adjust position if threshold is hit.
    """

    condition: str = Field(
        ...,
        min_length=10,
        max_length=500,
        description="Description of the break condition",
        examples=[
            "NIM compresses below 3.8% for two consecutive quarters",
            "Hyperscaler AI capex growth decelerates below 10% YoY",
            "SEBI introduces position limits for F&O market makers",
        ],
    )
    trigger_metric: str = Field(
        ...,
        max_length=200,
        description="Specific measurable metric to monitor",
        examples=["NIM", "Hyperscaler capex growth YoY", "SEBI F&O regulation"],
    )
    threshold: str = Field(
        ...,
        max_length=200,
        description="The level at which the thesis breaks",
        examples=["Below 3.8%", "Below 10% YoY", "Any new restrictive circular"],
    )
    probability: BreakProbability = Field(
        ...,
        description="Agent's assessment of likelihood this condition triggers",
    )
    data_source: str = Field(
        default="corpus",
        max_length=200,
        description="Source used to assess this break condition's probability",
        examples=["RBI Monetary Policy FY26", "Gartner AI Spending Forecast 2025"],
    )
    monitoring_frequency: Optional[str] = Field(
        default=None,
        description="How often to check this metric",
        examples=["Quarterly (earnings)", "Monthly (RBI data)", "Real-time (news)"],
    )
    triggered: bool = Field(
        default=False,
        description="True if current data shows this condition has already triggered",
    )
    related_assumption_ids: list[int] = Field(
        default_factory=list,
        description="IDs of assumptions this break condition is linked to",
    )

    @field_validator("condition", "trigger_metric", "threshold", mode="before")
    @classmethod
    def normalize_strings(cls, v: str) -> str:
        return v.strip() if isinstance(v, str) else v

    @computed_field
    @property
    def urgency_label(self) -> str:
        """UI urgency label combining probability and triggered status."""
        if self.triggered:
            return "TRIGGERED"
        if self.probability == "High":
            return "MONITOR CLOSELY"
        if self.probability == "Medium":
            return "WATCH"
        return "LOW RISK"

    @computed_field
    @property
    def urgency_color(self) -> Literal["red", "orange", "yellow", "green"]:
        if self.triggered:
            return "red"
        if self.probability == "High":
            return "orange"
        if self.probability == "Medium":
            return "yellow"
        return "green"


# ─────────────────────────────────────────────
# 4. DependencyNode
# ─────────────────────────────────────────────

class DependencyNode(BaseModel):
    """
    A single node in the thesis dependency chain.
    Used to build the visual A → B → C → D flow diagram.
    """

    id: int
    label: str = Field(..., max_length=60, description="Short label for the node")
    description: str = Field(default="", max_length=200)
    depends_on: list[int] = Field(default_factory=list)
    risk_score: Optional[int] = Field(
        default=None,
        ge=1,
        le=10,
        description="Risk score associated with this node (if applicable)",
    )
    is_terminal: bool = Field(
        default=False,
        description="True if this is the final outcome node",
    )

    @computed_field
    @property
    def node_color(self) -> Literal["red", "orange", "green", "gray"]:
        if self.risk_score is None:
            return "gray"
        if self.risk_score >= 7:
            return "red"
        if self.risk_score >= 4:
            return "orange"
        return "green"


# ─────────────────────────────────────────────
# 5. HistoricalAnalog
# ─────────────────────────────────────────────

class HistoricalAnalog(BaseModel):
    """
    A historical event/period that is structurally similar to the thesis.
    Helps investors understand precedent and potential outcomes.
    """

    title: str = Field(
        ...,
        max_length=200,
        description="Name of the historical analog",
        examples=[
            "Indian Banking NIM Expansion Cycle FY2003-2007",
            "Semiconductor Capex Cycle Peak 2022",
            "Telecom ARPU Compression 2017 (Jio Disruption)",
        ],
    )
    period: str = Field(
        ...,
        max_length=100,
        description="Time period of the analog",
        examples=["FY2003–FY2007", "2021–2022", "2017–2019"],
    )
    similarity_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="How similar this analog is to the current thesis (0.0–1.0)",
    )
    outcome: str = Field(
        ...,
        max_length=500,
        description="What happened in the historical analog",
    )
    lesson: str = Field(
        ...,
        max_length=500,
        description="Key lesson for the current thesis from this analog",
    )
    source: Optional[str] = Field(default=None, max_length=200)

    @computed_field
    @property
    def similarity_label(self) -> str:
        if self.similarity_score >= 0.75:
            return "Highly Similar"
        if self.similarity_score >= 0.5:
            return "Moderately Similar"
        return "Loosely Similar"


# ─────────────────────────────────────────────
# 6. QuantitativeFlag
# ─────────────────────────────────────────────

class QuantitativeFlag(BaseModel):
    """
    A quantitative inconsistency detected by Agent 5 within the thesis.
    Example: thesis claims 20% revenue CAGR but industry average is 8%.
    """

    field: str = Field(..., description="The metric flagged")
    thesis_claim: str = Field(..., description="What the thesis claims")
    corpus_data: str = Field(..., description="What the corpus data shows")
    discrepancy: str = Field(..., description="Description of the mismatch")
    severity: Literal["High", "Medium", "Low"] = Field(default="Medium")


# ─────────────────────────────────────────────
# 7. ThesisResponse
# ─────────────────────────────────────────────

class ThesisResponse(BaseModel):
    """
    Complete investment thesis validation response.
    Returned by POST /api/validate-thesis.

    Contains:
    - Extracted assumptions with confidence scores
    - Visual dependency chain
    - Risk scores per dimension (1–10)
    - Break conditions with trigger metrics
    - Historical analogs
    - Overall thesis strength and confidence
    - Supporting citations from corpus
    """

    # ── Core thesis ───────────────────────────
    thesis_text: str = Field(
        ...,
        description="The original thesis text that was validated",
    )

    # ── Verdict ───────────────────────────────
    thesis_strength: ThesisStrength = Field(
        ...,
        description=(
            "Overall thesis strength: Strong (avg risk <4), "
            "Medium (4–7), Weak (>7)"
        ),
    )
    structural_robustness: StructuralRobustness = Field(
        ...,
        description="How well the thesis logic holds together structurally",
    )
    confidence: ConfidenceLevel = Field(
        ...,
        description="Agent's confidence in the validation based on corpus coverage",
    )

    # ── Agent 6 outputs ───────────────────────
    assumptions: list[Assumption] = Field(
        default_factory=list,
        description="List of extracted assumptions from the thesis",
    )
    dependency_chain: list[str] = Field(
        default_factory=list,
        description="Ordered causal chain: ['AI Demand', 'Capex Growth', 'Revenue', 'Margins', 'Valuation']",
    )
    dependency_nodes: list[DependencyNode] = Field(
        default_factory=list,
        description="Structured dependency nodes for visual graph rendering",
    )

    # ── Agent 5 outputs ───────────────────────
    quantitative_flags: list[QuantitativeFlag] = Field(
        default_factory=list,
        description="Numerical inconsistencies detected in the thesis claims",
    )

    # ── Agent 7 outputs ───────────────────────
    risks: list[RiskScore] = Field(
        default_factory=list,
        description="Risk scores per dimension (demand, margin, valuation, etc.)",
    )
    break_conditions: list[BreakCondition] = Field(
        default_factory=list,
        description="Specific conditions that would invalidate the thesis",
    )
    historical_analogs: list[HistoricalAnalog] = Field(
        default_factory=list,
        description="Historical events structurally similar to this thesis",
    )
    synthesis: str = Field(
        default="",
        description="Agent's final synthesis paragraph summarizing the validation",
    )

    # ── Sources ───────────────────────────────
    citations: list[Citation] = Field(
        default_factory=list,
        description="Source documents used in the validation",
    )

    # ── Performance metadata ──────────────────
    latency_ms: int = Field(
        default=0,
        ge=0,
        description="Total pipeline execution time in milliseconds",
    )
    agents_used: list[str] = Field(
        default_factory=list,
        description="Agent names that processed this thesis",
    )
    cache_hit: bool = Field(default=False)
    request_id: Optional[str] = Field(default=None)
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
    )

    # ─────────────────────────────────────────
    # COMPUTED FIELDS
    # ─────────────────────────────────────────

    @computed_field
    @property
    def avg_risk_score(self) -> float:
        """Average risk score across all dimensions."""
        if not self.risks:
            return 0.0
        return round(sum(r.score for r in self.risks) / len(self.risks), 2)

    @computed_field
    @property
    def highest_risk(self) -> Optional[RiskScore]:
        """The single highest-scoring (most dangerous) risk dimension."""
        if not self.risks:
            return None
        return max(self.risks, key=lambda r: r.score)

    @computed_field
    @property
    def critical_assumptions(self) -> list[Assumption]:
        """Assumptions marked as critical (thesis breaks without them)."""
        return [a for a in self.assumptions if a.is_critical]

    @computed_field
    @property
    def unsupported_assumptions(self) -> list[Assumption]:
        """Assumptions with no historical support in corpus."""
        return [a for a in self.assumptions if not a.historical_support]

    @computed_field
    @property
    def triggered_break_conditions(self) -> list[BreakCondition]:
        """Break conditions that have already triggered."""
        return [b for b in self.break_conditions if b.triggered]

    @computed_field
    @property
    def high_probability_breaks(self) -> list[BreakCondition]:
        """Break conditions with High probability of triggering."""
        return [b for b in self.break_conditions if b.probability == "High"]

    @computed_field
    @property
    def assumption_support_rate(self) -> float:
        """Percentage of assumptions with historical corpus support."""
        if not self.assumptions:
            return 0.0
        supported = sum(1 for a in self.assumptions if a.historical_support)
        return round(supported / len(self.assumptions) * 100, 1)

    @computed_field
    @property
    def citation_count(self) -> int:
        return len(self.citations)

    @computed_field
    @property
    def within_latency_target(self) -> bool:
        return self.latency_ms <= 3000

    @computed_field
    @property
    def verdict_summary(self) -> str:
        """
        One-line verdict string for UI header display.
        e.g. "Medium Thesis | High Confidence | Avg Risk: 5.4/10"
        """
        return (
            f"{self.thesis_strength} Thesis | "
            f"{self.confidence} Confidence | "
            f"Avg Risk: {self.avg_risk_score}/10"
        )

    # ─────────────────────────────────────────
    # VALIDATORS
    # ─────────────────────────────────────────

    @model_validator(mode="after")
    def validate_thesis_strength_consistency(self) -> "ThesisResponse":
        """
        Validates that thesis_strength is consistent with avg_risk_score.
        Auto-corrects if Agent 7 made an error.
        """
        avg = self.avg_risk_score
        if avg == 0.0:
            return self  # No risks scored yet — skip validation

        expected_strength: ThesisStrength
        strong_threshold = THESIS_STRENGTH_THRESHOLDS.get("strong", 4.0)
        medium_threshold = THESIS_STRENGTH_THRESHOLDS.get("medium", 7.0)

        if avg < strong_threshold:
            expected_strength = "Strong"
        elif avg < medium_threshold:
            expected_strength = "Medium"
        else:
            expected_strength = "Weak"

        if self.thesis_strength != expected_strength:
            # Auto-correct silently (agents can be slightly off)
            object.__setattr__(self, "thesis_strength", expected_strength)

        return self

    @model_validator(mode="after")
    def validate_assumption_ids_unique(self) -> "ThesisResponse":
        """Ensures all assumption IDs are unique."""
        ids = [a.id for a in self.assumptions]
        if len(ids) != len(set(ids)):
            raise ValueError("Assumption IDs must be unique.")
        return self

    # ─────────────────────────────────────────
    # CONVENIENCE CONSTRUCTORS
    # ─────────────────────────────────────────

    @classmethod
    def error_response(
        cls,
        thesis_text: str,
        error_message: str,
        request_id: Optional[str] = None,
        latency_ms: int = 0,
    ) -> "ThesisResponse":
        """Creates a standardized error response for failed thesis validation."""
        return cls(
            thesis_text=thesis_text,
            thesis_strength="Weak",
            structural_robustness="Low",
            confidence="Low",
            synthesis=f"Thesis validation failed: {error_message}",
            latency_ms=latency_ms,
            request_id=request_id,
        )

    @classmethod
    def insufficient_data_response(
        cls,
        thesis_text: str,
        request_id: Optional[str] = None,
        latency_ms: int = 0,
    ) -> "ThesisResponse":
        """Creates a response when corpus has insufficient data for validation."""
        return cls(
            thesis_text=thesis_text,
            thesis_strength="Medium",
            structural_robustness="Low",
            confidence="Low",
            synthesis=(
                "Insufficient corpus data to fully validate this thesis. "
                "Please ingest relevant annual reports, earnings transcripts, "
                "and sector research before validation."
            ),
            latency_ms=latency_ms,
            request_id=request_id,
        )

    model_config = {"populate_by_name": True}


# ─────────────────────────────────────────────
# ThesisCompareResponse
# ─────────────────────────────────────────────

class ThesisCompareResponse(BaseModel):
    """
    Side-by-side comparison of two thesis validations.
    Returned by POST /api/thesis/compare.
    """

    thesis_a: ThesisResponse
    thesis_b: ThesisResponse
    winner: Literal["thesis_a", "thesis_b", "tie"] = Field(
        ...,
        description="Which thesis is stronger overall",
    )
    comparison_summary: str = Field(
        default="",
        description="Agent's summary of the comparative analysis",
    )
    latency_ms: int = Field(default=0)
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
    )

    @computed_field
    @property
    def risk_delta(self) -> float:
        """Difference in avg risk scores (A minus B). Positive = A is riskier."""
        return round(thesis_a_score - thesis_b_score, 2) if (
            thesis_a_score := self.thesis_a.avg_risk_score
        ) and (
            thesis_b_score := self.thesis_b.avg_risk_score
        ) else 0.0


# ─────────────────────────────────────────────
# EXPORTS
# ─────────────────────────────────────────────

__all__ = [
    "Assumption",
    "RiskScore",
    "BreakCondition",
    "DependencyNode",
    "HistoricalAnalog",
    "QuantitativeFlag",
    "ThesisResponse",
    "ThesisCompareResponse",
    "ThesisStrength",
    "StructuralRobustness",
    "BreakProbability",
    "AssumptionCategory",
    "RiskDimension",
]
